name: patient_care_statistics
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  omni_datetime_picker: ^1.0.9
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  uuid: ^4.3.3
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  date_time_format: ^2.0.1
  excel:
    git: 
      url: https://github.com/justkawal/excel.git
  permission_handler: ^11.3.0
  share_plus: ^7.2.2
  sqflite_common_ffi: ^2.3.2+1
  collection: ^1.18.0
  deep_pick: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
